sudo: true

language: python

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          group: edge
        - os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "trusty" ]]; apt install python-pip ; fi
  - pip install virtualenv
  - ./setup
script:
  - ./telemetry &
  - sleep 2
  - wget http://localhost:5001
# after_success: