sudo: true

language: python

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          group: edge
          before_install: apt install python-pip
        - os: osx
install:
  - pip install virtualenv
  - ./setup
script:
  - ./telemetry &
  - sleep 2
  - wget http://localhost:5001
# after_success: